Robo37/WebUI/Models/CartIndexViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

Robo37/WebUI/Models/CoursesListViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class CoursesListViewModel
    {
        public IEnumerable<Course> Courses { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentGenre { get; set; }
    }
}

Robo37/WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }    //Общее количество курсов
        public int ItemsPerPage { get; set; }  //Количество курсов на странице
        public int CurrentPage { get; set; }   //Номер текущей страницы
        public int TotalPages                  //Общее количество страниц
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

Robo37/WebUI/Controllers/AdminController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class AdminController : Controller
    {
        ICourseRepository repository;

        public AdminController(ICourseRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index()
        {
            return View(repository.Courses);
        }

        public ViewResult Edit(int courseId)
        {
            Course course = repository.Courses.FirstOrDefault(b => b.CourseId == courseId);

            return View(course);
        }
        [HttpPost]
        public ActionResult Edit(Course course)
        {
            if (ModelState.IsValid)
            {
                repository.SaveCourse(course);
                TempData["message"] = string.Format("Изменения информации о курсе \"{0}\" сохранены", course.Name);
                return RedirectToAction("Index");
            }
            else
            {
                return View(course);
            }
        }
    }
}

Robo37/WebUI/Controllers/CartController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class CartController : Controller
    {
        private ICourseRepository repository;
        private IOrderProcessor orderProcessor;

            public CartController(ICourseRepository repo, IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart( Cart cart, int courseId, string returnUrl)
        {
            Course course = repository.Courses
                .FirstOrDefault(b => b.CourseId == courseId);

            if (course != null)
                {
                    cart.AddItem(course, 1);
                }

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart( Cart cart, int courseId, string returnUrl)
        {
            Course course = repository.Courses
                .FirstOrDefault(b => b.CourseId == courseId);

            if (course != null)
            {
                cart.RemoveLine(course);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, корзина пуста!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(new ShippingDetails());
            }            
        }
    }
}

Robo37/WebUI/Controllers/CoursesController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class CoursesController : Controller
    {
        private ICourseRepository repository;
        public int pageSize = 2;
        
        public CoursesController(ICourseRepository repo)
        {
            repository = repo;
        }

        public ViewResult List(string genre, int page = 1)
        {
            CoursesListViewModel model = new CoursesListViewModel
            {
                Courses = repository.Courses
                .Where(b => genre == null || b.Genre == genre)
                .OrderBy(course => course.CourseId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = genre == null ? 
                        repository.Courses.Count() : 
                        repository.Courses.Where(course => course.Genre == genre).Count()
                },
                CurrentGenre = genre
            };

            return View(model);
        }
    }
}

Robo37/WebUI/Controllers/NavController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class NavController : Controller
    {
        private ICourseRepository repository;

        public NavController(ICourseRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string genre = null)
        {
            ViewBag.SelectedGenre = genre;

            IEnumerable<string> genres = repository.Courses
                .Select(course => course.Genre)
                .Distinct()
                .OrderBy(x => x);
            
            return PartialView("FlexMenu", genres);
        }
    }
}

Robo37/WebUI/Views/Admin/Edit.cshtml
@model Domain.Entities.Course

@{
    ViewBag.Title = "Админ панель: редактирование товара";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<div class="panel">
    <div class="panel-heading">
        <h3>Редактирование курса "@Model.Name"</h3>
    </div>

    @using (Html.BeginForm())
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.CourseId)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                if (property.PropertyName != "CourseId")
                {
                    <div class="form-group">
                        <label>@(property.DisplayName ?? property.PropertyName)</label>
                        @if (property.PropertyName == "Description")
                        {
                            @Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = 5 })
                        }
                        else
                        {
                            @Html.TextBox(property.PropertyName, null, new { @class = "form-control"})
                        }
                        @Html.ValidationMessage(property.PropertyName)
                    </div>
                }
            }
        </div>

        <div class="panel-footer">
            <input type="submit" value="Сохранить" class="btn btn-primary"/>
            @Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

Robo37/WebUI/Views/Admin/Index.cshtml
@model IEnumerable<Domain.Entities.Course>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="panel panel-default">
    <div class="panel-heading">
        Список курсов
    </div>

    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>                
                <th class="text-right">
                    @Html.DisplayNameFor(model => model.CourseId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Teacher)
                </th>
                <th class="text-right">
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th class="text-center">
                    Действия
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>                   
                    <td class="text-right">
                        @item.CourseId
                    </td>
                    <td>
                        @Html.ActionLink(item.Name, "Edit", new { item.CourseId})
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Teacher)
                    </td>
                    <td class="text-right">
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            @Html.Hidden("CourseId", item.CourseId)
                            <input type="submit" class="btn btn-default btn-xs" value="Удалить" />
                        }
                    </td>
                </tr>
            }

        </table>
    </div>

    <div class="panel-footer">
        @Html.ActionLink("Добавить", "Create", null, new { @class = "btn btn-default" })
    </div>
</div>

Robo37/WebUI/Views/Cart/Checkout.cshtml
@model Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "Курсы: форма заказа";
}

<h2>Оформить заказ</h2>
<p>Пожалуйта, введите Ваши контактные данные.</p>

@using (Html.BeginForm())
{
    @Html.ValidationSummary();
     <h3>Данные</h3>
     <div class="form-group">
         <label>Ваше имя:</label>
         @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
     </div>

    <h3>Адрес доставки:</h3>
    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName != "Name" && property.PropertyName != "GiftWrap")
        {
            <div class="form-group">
                <label>
                    @(property.DisplayName ?? property.PropertyName)
                </label>
                @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
            </div>
        }
    }

    <h3>Опции</h3>
        <div class="form-group">
            <label>
                @Html.EditorFor(x => x.GiftWrap)
                Использовать подарочную упаковку?
            </label>     
        </div>

        <div class="text-center">
            <input class="btn btn-primary" type="submit" value="Обработать заказ"/>
        </div>
}

Robo37/WebUI/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Заказ обработан";
}

<h2>Спасибо!</h2>
<p>Спасибо за выбор нашего центра! В ближайшее время договор будет отправлен.</p>

Robo37/WebUI/Views/Cart/Index.cshtml
@model WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "Курсы: Ваша корзина";
}

<h2>@ViewBag.Title</h2>

<table id="cartTable" class="table">
    <thead>
        <tr>
            <th>Количество</th>
            <th>Наименование</th>
            <th class="text-right">Цена</th>
            <th class="text-right">Сумма</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Course.Name - @line.Course.Teacher</td>
                <td class="text-right">@line.Course.Price.ToString("# руб\\.")</td>
                <td class="text-right">@((line.Quantity * line.Course.Price).ToString("# руб\\."))</td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("CourseId", line.Course.CourseId)
                        @Html.HiddenFor(x => x.ReturnUrl)
                        <input class="btn btn-sm btn-warning" type="submit" value="Удалить"/>
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Итого:</td>
            <td class="text-right">
            @Model.Cart.ComputeTotalValue().ToString("# руб\\.")
            </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Продолжить покупки</a>
    @Html.ActionLink("Оформить заказ", "Checkout", null, new { @class = "btn btn-primary"})
</div>

Robo37/WebUI/Views/Cart/Summary.cshtml
@model Domain.Entities.Cart

<div class = "navbar-right hidden-xs">
    @Html.ActionLink("Заказать", "Index", "Cart",
    new { returnUrl = Request.Url.PathAndQuery },
          new { @class = "btn btn-default navbar-btn" })
</div>

<div class="navbar-right visible-xs">
    <a href="@Url.Action("Index", "Cart", new {returnUrl = Request.Url.PathAndQuery })" class="btn btn-default navbar-btn">
        <span class="glyphicon glyphicon-shopping-cart"></span>
    </a>
</div>

<div class = "navbar-text navbar-right">
    <b class="hidden-xs"> Ваша корзина</b> 
    @Model.Lines.Sum(x => x.Quantity) книг,
    @Model.ComputeTotalValue().ToString("# руб")
</div>

Robo37/WebUI/Views/Courses/List.cshtml
@using WebUI.Models
@model CoursesListViewModel

@{
    ViewBag.Title = "Курсы";
}

@foreach (var course in Model.Courses)
{
    @Html.Partial("_CourseSummary", course)
}

<div class="btn-group pull-left-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new {  page = x, genre = Model.CurrentGenre}))
</div> 

       

Robo37/WebUI/Views/Nav/FlexMenu.Mobile.cshtml
@model IEnumerable<string>

<div data-role="navbar">
    <ul>

        @foreach (var link in Model)
            {
            <li>
                @Html.RouteLink(link, new
               {
                   controller = "Courses",
                   action = "List",
                   genre = link,
                   page = 1
               }, new
               {
                   data_transition = "fade",
                   @class = (link == ViewBag.SelectedGenre ? " ui-btn-active" : null)
               })
            </li>
        }

    </ul>
</div>

Robo37/WebUI/Views/Nav/FlexMenu.cshtml
@model IEnumerable<string>

@{ 
    bool horizontal = (bool)(ViewContext.RouteData.Values["horizontalNav"] ?? false);
    string wrapperClasses = horizontal ? "btn-group btn-group-sm btn-group-justified" : null;
}

<div class="@wrapperClasses">
    @Html.ActionLink("Домой", "List", "Courses", null,
    new
    {
        @class = horizontal ? "btn btn-default btn-sm" : 
        "btn btn-block btn-default btn-lg"
    })

    @foreach (var link in Model)
    {
        @Html.RouteLink(link, new
   {
       controller = "Courses",
       action = "List",
       genre = link,
       page = 1
   }, new
   {
       @class = (horizontal ? "btn btn-default btn-sm" :
       "btn btn-block btn-default btn-lg")
       + (link == ViewBag.SelectedGenre ? " btn-primary" : "")
   })
    }
</div>

Robo37/WebUI/Views/Shared/_AdminLayout.cshtml
@{ 
    Layout = null;
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">
                @TempData["message"]
            </div>
        }
        @RenderBody()
    </div>
</body>
</html>

Robo37/WebUI/Views/Shared/_CourseSummary.Mobile.cshtml
@model Domain.Entities.Course

<div data-role="collapsible" data-collapsed="false" data-content-theme="c">
    <h2>@Model.Name</h2>
    <h3>@Model.Teacher</h3>

    <div>
        <div>
            @Model.Description
        </div>
        <div>
            <strong>@Model.Price.ToString("# руб\\.")</strong>
        </div>
        <div>
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                @Html.HiddenFor(x => x.CourseId)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="В корзину" />
            }
        </div>
    </div>
</div>

Robo37/WebUI/Views/Shared/_CourseSummary.cshtml
@model Domain.Entities.Course

<div class="well">
    <div class="row">
        <div class="col-xs-9">
            <h3>
                <strong>@Model.Name</strong>
            </h3>
            <h4>
                <strong>@Model.Teacher</strong>
            </h4>
        </div>
        <div class="col-xs-3">
            <h3>
                <strong id="price" class="pull-right label label-primary">
                    @Model.Price.ToString("# руб\\.")
                </strong>
            </h3>
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                <div class="pull-right">
                    @Html.HiddenFor(x => x.CourseId)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                    <input type="submit" class="btn btn-success" value="В корзину"/> 
                </div>
            }
        </div>
    </div>
    <span class="lead">@Model.Description</span>
</div>

Robo37/WebUI/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet"
          href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div data-role="page" id="page1">
        <div data-theme="a" data-role="header" data-position="fixed">
            <h3>Robo37</h3>
            @Html.Action("Menu", "Nav")
        </div>

        <div data-role="content">
            <ul data-role="listview" data-dividertheme="b" data-inset="false">
                <li>@RenderBody()</li>
            </ul>
        </div>        
    </div>
</body>
</html>

Robo37/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title>@ViewBag.Title </title>
</head>
<body>
    <div class="navbar navbar-inverse">
        <a class="navbar-brand" href="#"> 
            <span class="hidden-xs">Robo37 - Робототехника в Иванове</span>
            <div class="visible-xs">Robo37</div>
        </a>
        @Html.Action("Summary", "Cart") 
    </div>

    <div class="visible-xs">
        @Html.Action("Menu", "Nav", new { horizontalNav = true})
    </div>
    
    <div class="row panel">
        <div id="genres" class="col-sm-3 hidden-xs">
            @Html.Action("Menu", "Nav");
        </div>
        <div class="col-xs-12 col-sm-8">
            @RenderBody()
        </div>
    </div>
        
</body>
</html>